### ISSUE TITLE
OSError Saving Selected Layers

### ISSUE THREAD

**Issue by kailynkfields** [brainglobe/brainglobe-napari-io#2]
When saving a selected layer as a XML file in Napari, receives the following error (Linux-based computer)

`OSError: File path\to\file.xml save failed. No data written! There may be no plugins capable of writing these 1 layers to path\to\file.xml`

Napari will save to a CSV though.

**Comment by adamltyson** [comment]
There seems to be a problem saving a single layer. I'll look into it. In the meantime, if you select both the cell and non-cell layer, then saving should work (into a single file).

**Comment by adamltyson** [comment]
This should be fixed now if you run `pip install brainglobe-napari-io --upgrade`.
