### ISSUE TITLE
[BUG] Mismatched and un-used dependencies.

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/brainglobe-napari-io#44]
[Autoupdate on conda-forge](https://github.com/conda-forge/brainglobe-napari-io-feedstock/pull/3) fails due to change in dependency from `imlib` to `brainglobe-utils`.

But it also appears that:
- `numpy` and `pandas` are not included as dependencies despite the fact that they are hard-dependencies.
- `napari-ndtiffs`, & `napari-plugin-engine` are still used in the base package but conda reports that they are not used. This should be investigated, and they should be removed if this is the case.

**Comment by adamltyson** [comment]
> napari-ndtiffs, & napari-plugin-engine are still used in the base package but conda reports that they are not used. This should be investigated, and they should be removed if this is the case.

Pretty sure both of these can removed now. The necessary `napari-ndtiffs` functionality is in base napari, and `napari-plugin-engine` has been replaced with `npe2` (a napari dependency).

**Comment by willGraham01** [comment]
Closed with #45
